version: '3'
services:
    database:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password --disable-log-bin
        restart: always
        container_name: mysql
        volumes:
            - .docker/data/mysql:/var/lib/mysql
            - .docker/data/log:/var/log
        env_file:
            - .env.mysql
        ports:
            - 3306:3306
        networks:
            - app

    php-apache:
        build:
            context: ./
            dockerfile: .docker/php/Dockerfile
        container_name: php-apache
        volumes:
            - .:/var/www
            - .docker/data/log:/var/log
        depends_on:
            - database
        networks:
            - app
        ports:
          - 80:80
networks:
    app:
