version: '3'
networks:
  app: null
services:
  php-apache:
    container_name: php-apache
    image: mcneely/rehabcc_php-apache:1560268344
    networks:
      - app
    ports:
      - 80:80
    environment:
      - APP_ENV=prod
      - APP_SECRET=6373d9eeebsdfgsd39d21b3af4aa6f1d22bcef
      - DATABASE_URL=mysql://mysql:mysql@rehabcc.cwbnwms6azwt.us-east-2.rds.amazonaws.com:3306/rehabcc
